### 2. Numpy 연산
연산을 통한 결과

In [2]:
import numpy as np
t_a=np.arange(1,11)
t_a.sum()

55

In [4]:
t_a=np.arange(1,13).reshape(3,4)
t_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
t_a.sum(axis=0)#제일 고차원의 축!

array([15, 18, 21, 24])

In [6]:
t_a.sum(axis=1)

array([10, 26, 42])

In [7]:
t_a_2=np.array([t_a,t_a,t_a])

In [8]:
t_a_2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [9]:
t_a_2.shape

(3, 3, 4)

In [11]:
t_a_2.sum(axis=0)#3
t_a_2.sum(axis=1)#2
t_a_2.sum(axis=2)#1

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [18]:
v_a=np.array([[1,2,3],[1,2,3,]])
v_a_1=np.array([4,5,6])
np.vstack((v_a,v_a_1))#한번더 묶어야한다.#결합하는 차원원소의 개수가 동일해야한다.

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [19]:
v_a=np.array([1,2,3])
v_a_1=np.array([4,5,6])
np.vstack((v_a,v_a_1)).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
h_1=v_a.reshape(-1,1)
h_2=v_a_1.reshape(-1,1)
np.hstack((h_1,h_2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
x=np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [24]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
x%x

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [27]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [28]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [29]:
x==x

array([[ True,  True,  True],
       [ True,  True,  True]])

In [31]:
heights=np.array([1.83,1.76,1.69,1.86,1.77,1.73])
weights=np.array([86,74,59,95,80,68])
BMI=weights/(heights**2)
BMI

array([25.68007405, 23.88946281, 20.65754   , 27.45982194, 25.53544639,
       22.72043837])

In [32]:
x=np.arange(1,7).reshape(2,3)
y=np.arange(1,7).reshape(3,2)
np.dot(x,y)

array([[22, 28],
       [49, 64]])

In [33]:
x.dot(y) #내적 매우 중요.

array([[22, 28],
       [49, 64]])

In [34]:
x+1#각각자리수연산= 브로드캐스팅 연산!!

array([[2, 3, 4],
       [5, 6, 7]])

In [35]:
x=np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
v=np.array([10,20,30])
v

array([10, 20, 30])

In [37]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [38]:
v2=np.array([1,2,3,4]).reshape(-1,1)
v2

array([[1],
       [2],
       [3],
       [4]])

In [39]:
x+v2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [40]:
v+v2 #브로드캐스팅(자연스럽게 확장된다.)

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [41]:
x=np.arange(3,10)
x

array([3, 4, 5, 6, 7, 8, 9])

In [42]:
(x>5)

array([False, False, False,  True,  True,  True,  True])

In [43]:
(x>5).all()

False

In [44]:
(x>5).any()

True

In [45]:
(x<1).all()

False

In [46]:
(x<1).any()

False

In [47]:
(x>2).all()

True

In [48]:
(x>2).any()

True

In [49]:
x=np.random.randint(1,100,100)

In [50]:
x

array([18, 69, 85, 11,  2, 64, 59, 78, 36, 19, 51, 83, 10, 61, 18,  3, 51,
       44, 59, 21, 13, 30, 20, 51, 86, 58, 52, 77, 95, 49, 57, 15,  5, 87,
       40, 16, 88, 77, 60, 30,  3, 51, 41, 18, 20, 17, 24, 79, 88, 82, 46,
       91,  7, 50, 12, 60, 10, 55, 54, 70, 29, 11, 97, 20,  3, 11, 83, 88,
       15, 15, 79, 42, 38,  3, 43, 10, 29, 46, 52, 91, 29,  8, 96, 88, 55,
       96, 59, 48, 96, 72, 86, 36, 96, 74, 34, 86,  2, 86, 17, 35])

In [52]:
x=np.random.randint(0,100,100)
if np.mean(x)>=50:
    print("전원통과")
if (x>=50).all():
    print("학년1등")
if (x==100).any():
    print("전교1등반")

전원통과


In [55]:
x=np.array([1,2,3,4,5,1])
np.where(x==1,10,20)#참일때 10, 거짓일때 20#'10','20'도 가능.

array([10, 20, 20, 20, 20, 10])

In [56]:
d=np.array([1,5,3,7,2,8,4])
np.argsort(d) #어떤게 작은지 순서대로.

array([0, 4, 2, 6, 1, 3, 5], dtype=int64)

In [57]:
np.argmax(d)#가장큰 데이터가 어디 위치하는지

5

In [58]:
np.argmin(d)#가장 작은 값이 어디 위치하는지.

0

In [59]:
d>=5

array([False,  True, False,  True, False,  True, False])

In [60]:
d[d>=5]

array([5, 7, 8])

In [61]:
(d>=5).shape

(7,)

In [62]:
d.shape #동일한 크기여야 연산가능.

(7,)

In [63]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
l=np.array([0,5,9,0,0,0])
x[l]

array([ 1,  6, 10,  1,  1,  1])

In [69]:
x=x.reshape(2,-1)
i_1=np.array([0,1])
i_0=np.array([1,0])
print(x)
x[i_0,i_1] # 팬시 인덱스 #넘파이 끝.!

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([6, 2])

In [70]:
#데이터=배열형태,동일한사이즈 필요.
#연산,인덱스(똑같은사이즈) 대괄호가 차원을 구분할 수 있다.(콤마도가능)
#콤마로 차원을 구분할 수 있다. 스칼라~브로드캐스트 연산 등 가능. for 없이 연산가능
x_l=np.array([x,x,x])

In [71]:
x_l=np.array([x,x,x])
x_l

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [72]:
x_l[:,:,:4]

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]]])