In [9]:
import numpy as np
import pandas as pd
data = pd.read_csv('data1_all.csv')
data_X = data[['Weight','Length','Diagonal','Height','Width']].to_numpy()
data_Y = data['Name'].to_numpy()
#data_Y.shape # name에 [] 하나없애면 차원 없어진다.

#2. data 전처리
from sklearn.preprocessing import StandardScaler
ss = StandardScaler().fit(data_X) # 지도학습이 아님.
data_X = ss.transform(data_X)

#3. data분리
from sklearn.model_selection import train_test_split
t_x, tt_x, t_y, tt_y = train_test_split(data_X, data_Y, random_state=42)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C = 20, max_iter = 1000) # 다중 분류용 C가 뭐지?
lr.fit(t_x, t_y)
lr.score(t_x, t_y), lr.score(tt_x, tt_y)
d = lr.decision_function(t_x[:1])
from scipy.special import softmax # 다중분류 -> 소프트맥스
np.round(softmax(d))

array([[1., 0., 0., 0., 0., 0., 0.]])

In [2]:
i = (t_y == 'A')|(t_y == 'G')
b_t_x = t_x[i]
b_t_y = t_y[i]
lr = LogisticRegression() 
lr.fit(b_t_x, b_t_y)

LogisticRegression()

In [3]:
lr.coef_, lr.intercept_

(array([[-0.41981254, -0.60056128, -0.68786241, -1.00159093, -0.74532495]]),
 array([-2.1898649]))

In [4]:
d = lr.decision_function(b_t_x[:1]) # 학습된 공식을 꺼내는 함수

In [5]:
from scipy.special import expit #exp의 역함수??
expit(d) 
# 이진분류 할 때 시그모이드 함수 사용한다.

array([0.00254817])