## 1.Numpy 생성
넘파이 실행 내용

In [69]:
import numpy as np

넘파이 외부모듈 호출

In [3]:
t_arr=np.array([1,4,5,8],float)
t_arr

array([1., 4., 5., 8.])

In [4]:
type(t_arr)

numpy.ndarray

In [5]:
type(t_arr[0])

numpy.float64

In [6]:
print(t_arr.dtype)

float64


In [7]:
print(t_arr.shape)

(4,)


In [8]:
mix=[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(mix).shape #왼쪽이 고차원

(3, 4)

In [13]:
t_3=[[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
    ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
    ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
    ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(t_3).shape

(4, 3, 4)

In [15]:
np.array(t_3).size

48

In [14]:
np.array([[1,2,3],[4,5,6]],dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
t_3=[[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
    ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
    ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
    ,[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(t_3).ndim

3

In [17]:
x=np.array([[1,2,5,8],[1,2,5,8]])
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [19]:
x=np.array([0,1,2,3,4,5,6,7])
#x.reshape(2,2)#불가능 x.reshape(3,-1)불가능.
x.reshape(2,-1)#-1 알아서 해준다.

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
x.reshape(2,2,-1) #저차원의 크기는 서로 같아야한다.

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
x=np.array([[1,2,3,4],[5,6,7,8]])
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
l=[[1,2,3,4],[5,6,7,8]]
l[0][0]
#l[0,0] 불가능

1

In [28]:
x=np.array(l)
x[0][0]
x[1,0]#왼쪽이 고차원

5

In [30]:
x=np.array([[[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5]],[[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5]]])
x.shape

(2, 3, 5)

In [32]:
x[1,2,3] #인덱스 0부터 시작.

4

In [34]:
x=np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]])
x[:,2]#왼쪽=>2차원

array([5, 5, 5, 5])

In [36]:
x[:2,:] #2인덱스전까지

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [38]:
x[:2,::2] #[시작인덱스:마지막인덱스:증감]

array([[1, 5],
       [1, 5]])

In [40]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
np.arange(1,100,10)#시작,끝,증감

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [48]:
np.ones(2)

array([1., 1.])

In [50]:
np.ones(shape=(2,2,10))#+2 같이 스칼라 연산하면 각각자리에 연산이 다 일어난다.

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [53]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [55]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [57]:
np.full((2,2),1)

array([[1, 1],
       [1, 1]])

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
x=np.arange(1,101)[::2]#(1,101,2)

In [62]:
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [64]:
np.zeros_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [71]:
np.zeros_like(x)#np.empty_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [81]:
np.identify(4)

AttributeError: module 'numpy' has no attribute 'identify'

In [75]:
np.eye(N=3,M=5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [78]:
mix=np.arange(9).reshape(3,3)
mix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
np.diag(mix,k=1)

array([1, 5])