## 벡터와 행렬연산(텐서)

In [1]:
import numpy as np

In [2]:
d = np.array(5)
print(d)
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

5
텐서의 차원 : 0
텐서의 크기(shape) : ()


In [3]:
d = np.array([1, 2, 3, 4])
print(d)
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

[1 2 3 4]
텐서의 차원 : 1
텐서의 크기(shape) : (4,)


In [4]:
# 3행 4열의 행렬
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d)
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
텐서의 차원 : 2
텐서의 크기(shape) : (3, 4)


In [5]:
d = np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print(d)
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)
# 3,5인 행렬이 두개가 모였다로 해석해도 된다.

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [19 20 21 22 23]
  [23 24 25 26 27]]]
텐서의 차원 : 3
텐서의 크기(shape) : (2, 3, 5)


## 행렬의 내적 (dot product)

In [7]:
A = np.array([[1, 3],[2, 4]])
B = np.array([[5, 7],[6, 8]])
print('두 행렬의 행렬곱 :')
print(np.matmul(A, B))

두 행렬의 행렬곱 :
[[23 31]
 [34 46]]
