DictVectorizer=> BOW 인코딩 벡터

In [1]:
from sklearn.feature_extraction import DictVectorizer

In [5]:
v = DictVectorizer(sparse=False) # sparse=False 로 하면 numpy array로 바뀐다.
D = [{'A':1,'B':2}, {'B':3,'C':1}] # 3종 -> 'A' -0
X = v.fit_transform(D)
X

array([[1., 2., 0.],
       [0., 3., 1.]])

In [6]:
v.feature_names_ # 특징이 A,B,C

['A', 'B', 'C']

In [7]:
D2 = {'A':5,'B':1,'D':100}

In [8]:
v.transform(D2) #  학습이 안된 D를 날린채로 나타낸다.

array([[5., 1., 0.]])

CountVectorizer => BOW 인코딩 벡터 문서의 집합 -> 단어토큰생성 -> 각 단어의 수를 카운트한다.

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?',
]

In [12]:
v1 = CountVectorizer()
v1.fit(corpus)
v1.vocabulary_

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 2,
 'document': 1,
 'second': 6,
 'and': 0,
 'third': 8,
 'one': 5,
 'last': 4}

In [16]:
v1.transform(['This is the first document.']).toarray() # 리스트로 전달해야한다.
# 원핫인코딩과 다른 작업이다.

array([[0, 1, 1, 1, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [17]:
v1.transform(['This is the first document. data']).toarray() # 학습되어있지 않은 것은 날려버린다.

array([[0, 1, 1, 1, 0, 0, 0, 1, 0, 1]], dtype=int64)