In [1]:
A = set([1,2,3,4,5])
B = set([4,5,6,7])
A | B # 합집합

{1, 2, 3, 4, 5, 6, 7}

In [2]:
A & B # 교집합

{4, 5}

In [3]:
data1 = '안녕 나는 오늘 힘들어'.split()
data2 = '안녕 못해 나는 지금 너무 힘들어'.split()
data1

['안녕', '나는', '오늘', '힘들어']

In [4]:
un = set(data1) | set(data2)
un

{'나는', '너무', '못해', '안녕', '오늘', '지금', '힘들어'}

In [5]:
intd = set(data1) & set(data2)
intd

{'나는', '안녕', '힘들어'}

In [6]:
len(intd)/len(un)

0.42857142857142855

In [7]:
data1 = '안녕 나는 오늘 힘들어.'
data2 = '안녕 못해 나는 지금 너무 힘들어'

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
t_v = TfidfVectorizer()
m_data = t_v.fit_transform([data1,data2])
m_data.toarray()

array([[0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087],
       [0.33471228, 0.47042643, 0.47042643, 0.33471228, 0.        ,
        0.47042643, 0.33471228]])

In [9]:
m_data

<2x7 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [10]:
t_v.vocabulary_

{'안녕': 3, '나는': 0, '오늘': 4, '힘들어': 6, '못해': 2, '지금': 5, '너무': 1}

In [11]:
idf = t_v.idf_
idf

array([1.        , 1.40546511, 1.40546511, 1.        , 1.40546511,
       1.40546511, 1.        ])

In [12]:
m_data[0:1].toarray()

array([[0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087]])

In [13]:
from sklearn.metrics import jaccard_score
import numpy as np
#jaccard_score(m_data[0:1],m_data[1:2])
jaccard_score(np.array([0,1,0,0]),np.array([0,1,1,2]), average=None)

array([0.33333333, 0.5       , 0.        ])

유클리드 유사도

In [14]:
def f(A,B):
    return np.sqrt(np.sum((A-B)**2))

In [15]:
A = np.array([0,1,2,3,4])
B = np.array([1,0,1,2,3])
f(A,B)

2.23606797749979

In [16]:
from sklearn.metrics import euclidean_distances
euclidean_distances(m_data[0:1],m_data[1:2])

array([[1.0486415]])

In [17]:
m_data.toarray()

array([[0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087],
       [0.33471228, 0.47042643, 0.47042643, 0.33471228, 0.        ,
        0.47042643, 0.33471228]])

In [18]:
# 정규화
def e_f(m):
    return m/np.sum(m)

In [19]:
e_data = e_f(m_data)

In [20]:
euclidean_distances(e_data[0:1],e_data[1:2])

array([[0.23884449]])

멘하탄 유사도, 멘하탄 거리

In [21]:
a = np.array([-1,2,3])
b = np.array([1,3,-4])
abs(-1) # abs 절대값연산 함수

1

In [22]:
np.sum(abs(a-b))

10

In [23]:
def f(A,B):
    return np.sum(abs((A-B)))

In [24]:
A = np.array([0,1,2,3,4])
B = np.array([1,0,1,2,3])
f(A,B)
# 거리는 수치 값이 낮은게 좋은거다.

5

유클리드 거리, 맨하탄 거리 유사도 확인

In [25]:
euclidean_distances(m_data[0:1],m_data[1:2])

array([[1.0486415]])

In [26]:
from sklearn.metrics.pairwise import manhattan_distances
manhattan_distances(m_data[0:1],m_data[1:2])

array([[2.38220441]])

정규화된 data 유클리드거리와 맨하탄 거리 유사도 확인

In [27]:
euclidean_distances(e_data[0:1],e_data[1:2])

array([[0.23884449]])

In [28]:
manhattan_distances(e_data[0:1],e_data[1:2])

array([[0.54258429]])

In [29]:
data1 = '안녕 나는 오늘 힘들어.'
data2 = '안녕 못해 나는 지금 너무 힘들어'
data3 = '나는 너무 즐거워'
from sklearn.feature_extraction.text import TfidfVectorizer
t_v = TfidfVectorizer()
m_data = t_v.fit_transform([data1,data2,data3])

In [30]:
# 정규화
def e_f(m):
    return m/np.sum(m)
e_data = e_f(m_data)

정규화 안한 DATA를 이용한 유클리드 거리 계산

In [31]:
euclidean_distances(m_data[0:1],m_data[1:2]),euclidean_distances(m_data[1:2],m_data[2:3])

(array([[1.02891385]]), array([[1.15714912]]))

In [32]:
ck1 = euclidean_distances(m_data[0:1],m_data[1:2])
ck2 = euclidean_distances(m_data[1:2],m_data[2:3])
ck1 = ck1/ck1
ck2 = ck2/ck1
ck1-ck2

array([[-0.15714912]])

In [33]:
ck1,ck2

(array([[1.]]), array([[1.15714912]]))

정규화 한 DATA를 이용한 유클리드 거리 계산

In [34]:
euclidean_distances(e_data[0:1],e_data[1:2]),euclidean_distances(e_data[1:2],e_data[2:3])

(array([[0.16949987]]), array([[0.19062493]]))

In [35]:
euclidean_distances(e_data[0:1],e_data[1:2])-euclidean_distances(e_data[1:2],e_data[2:3])

array([[-0.02112506]])

In [36]:
e_ck1 = euclidean_distances(e_data[0:1],e_data[1:2])
e_ck2 = euclidean_distances(e_data[1:2],e_data[2:3])
e_ck1 = e_ck1/e_ck1
e_ck2 = e_ck2/e_ck1
e_ck1-e_ck2

array([[0.80937507]])

In [37]:
abs(ck1-ck2),abs(e_ck1-e_ck2)
# 거리로 유사도를 판명할 때는 항상 정규화 해야한다.유사성 판명을 더 명확하게 할 수 있다.

(array([[0.15714912]]), array([[0.80937507]]))

정규화 안한 DATA를 이용한 맨하탄 거리 계산

In [38]:
manhattan_distances(m_data[0:1],m_data[1:2]),manhattan_distances(m_data[1:2],m_data[2:3])

(array([[2.28685493]]), array([[2.76734191]]))

In [39]:
manhattan_distances(m_data[0:1],m_data[1:2])-manhattan_distances(m_data[1:2],m_data[2:3])

array([[-0.48048698]])

In [40]:
manhattan_distances(e_data[0:1],e_data[1:2]),manhattan_distances(e_data[1:2],e_data[2:3])

(array([[0.37672893]]), array([[0.45588277]]))

In [41]:
manhattan_distances(e_data[0:1],e_data[1:2])-manhattan_distances(e_data[1:2],e_data[2:3])

array([[-0.07915384]])

In [42]:
ck1 = euclidean_distances(m_data[0:1],m_data[1:2])
ck2 = euclidean_distances(m_data[1:2],m_data[2:3])
ck1 = ck1/ck1
ck2 = ck2/ck1
ck1-ck2
e_ck1 = euclidean_distances(e_data[0:1],e_data[1:2])
e_ck2 = euclidean_distances(e_data[1:2],e_data[2:3])
e_ck1 = e_ck1/e_ck1
e_ck2 = e_ck2/e_ck1
e_ck1-e_ck2
print("유클리드 거리를 이용한 거리 계산")
print(f'정규화 전 data이용 거리 계산 {abs(ck1-ck2)}')
print(f'정규화 후 data이용 거리 계산 {abs(e_ck1-e_ck2)}')

유클리드 거리를 이용한 거리 계산
정규화 전 data이용 거리 계산 [[0.15714912]]
정규화 후 data이용 거리 계산 [[0.80937507]]


In [43]:
ck1 = manhattan_distances(m_data[0:1],m_data[1:2])
ck2 = manhattan_distances(m_data[1:2],m_data[2:3])
ck1 = ck1/ck1
ck2 = ck2/ck1
ck1-ck2
e_ck1 = manhattan_distances(e_data[0:1],e_data[1:2])
e_ck2 = manhattan_distances(e_data[1:2],e_data[2:3])
e_ck1 = e_ck1/e_ck1
e_ck2 = e_ck2/e_ck1
e_ck1-e_ck2
print("맨하탄 거리를 이용한 거리 계산")
print(f'정규화 전 data이용 거리 계산 {abs(ck1-ck2)}')
print(f'정규화 후 data이용 거리 계산 {abs(e_ck1-e_ck2)}')

맨하탄 거리를 이용한 거리 계산
정규화 전 data이용 거리 계산 [[1.76734191]]
정규화 후 data이용 거리 계산 [[0.54411723]]
